version: 2
jobs:
  build:
    machine:
      java:
        version: oraclejdk8

    working_directory: ~/whoisspy

    steps:

      - checkout

      - run: ./gradlew clean build

      - run: ./gradlew jar

      - store_artifacts:
          path: target/who-is-spy.jar
  deployment:
    prod:
      branch: master
      commands:
      - ssh 13.58.222.23
